mptcp: add-addr: sending ADD_ADDR with port
Up to now, only the reception of these ADD_ADDR with ports was being
validated. These new simple tests cover the sending part.

For the sending part, it is required to tell the PM to create such
ADD_ADDR with a specific port. Prior to that, a listener socket will be
created to accept future MP_JOIN sent to this other port number. It is
then also required to do something to avoid a "create listen socket
error: -99", e.g. attaching the new address to the interface.

Note: it is currently not possible to send an ADD_ADDRv6 with a port
when TCP timestamps is being used [1]. Instead, the test just checks
that a "pure ACK" is sent.

Link: https://github.com/multipath-tcp/mptcp_net-next/issues/448 [1]
Signed-off-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>