packetdrill: mptcp: fix CLang errors
When compiling with CLang and the default options, some errors cause the
build to fail:

  queue/queue.c:52:14: error: array index 255 is past the end of the array (that has type 'void *[255]') [-Werror,-Warray-bounds]
     52 |                 *element = queue->elements[QUEUE_SIZE];
        |                            ^               ~~~~~~~~~~
  queue/queue.h:26:2: note: array 'elements' declared here
     26 |         void *elements[QUEUE_SIZE];
        |         ^
  queue/queue.c:113:14: error: array index 255 is past the end of the array (that has type 'u64[255]' (aka 'unsigned long long[255]')) [-Werror,-Warray-bounds]
    113 |                 *element = queue->elements[QUEUE_SIZE];
        |                            ^               ~~~~~~~~~~
  queue/queue.h:50:2: note: array 'elements' declared here
     50 |         u64 elements[QUEUE_SIZE];
        |         ^
  2 errors generated.
  make: *** [<builtin>: queue/queue.o] Error 1
  make: *** Waiting for unfinished jobs....
  mptcp.c:721:10: error: variable 'subflow' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
    721 |         else if(direction == DIRECTION_OUTBOUND){
        |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  mptcp.c:732:6: note: uninitialized use occurs here
    732 |         if(!subflow)
        |             ^~~~~~~
  mptcp.c:721:7: note: remove the 'if' if its condition is always true
    721 |         else if(direction == DIRECTION_OUTBOUND){
        |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  mptcp.c:718:28: note: initialize the variable 'subflow' to silence this warning
    718 |         struct mp_subflow *subflow;
        |                                   ^
        |                                    = NULL
  mptcp.c:1837:54: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   1837 |                 if(add_addr_script->data.add_addr.ipv4_w_port.port == UNDEFINED)
        |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:1843:54: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   1843 |                 if(add_addr_script->data.add_addr.ipv6_w_port.port == UNDEFINED)
        |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:1887:54: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   1887 |                 if(add_addr_script->data.add_addr.ipv4_w_port.port == UNDEFINED)
        |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:1894:54: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   1894 |                 if(add_addr_script->data.add_addr.ipv6_w_port.port == UNDEFINED)
        |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:1974:55: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   1974 |                         if(add_addr_script->data.add_addr.ipv4_w_port.port == UNDEFINED)
        |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:1987:60: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   1987 |                         if(add_addr_script->data.add_addr.ipv4_w_port_hmac.port == UNDEFINED)
        |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:2000:55: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   2000 |                         if(add_addr_script->data.add_addr.ipv6_w_port.port == UNDEFINED)
        |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:2013:60: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   2013 |                         if(add_addr_script->data.add_addr.ipv6_w_port_hmac.port == UNDEFINED)
        |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:2036:55: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   2036 |                         if(add_addr_script->data.add_addr.ipv4_w_port.port == UNDEFINED)
        |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:2049:55: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   2049 |                         if(add_addr_script->data.add_addr.ipv4_w_port.port == UNDEFINED)
        |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:2062:55: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   2062 |                         if(add_addr_script->data.add_addr.ipv6_w_port.port == UNDEFINED)
        |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  mptcp.c:2075:55: error: result of comparison of constant -1 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
   2075 |                         if(add_addr_script->data.add_addr.ipv6_w_port.port == UNDEFINED)
        |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~
  13 errors generated.
  make: *** [<builtin>: mptcp.o] Error 1
  clang -g -Wall -Werror -Wno-address-of-packed-member -c parser.c
  parser.y:710:11: error: variable 'opt' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
    710 |         }else if(dsn_type==8 && dack_type==8){
        |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  parser.y:719:45: note: uninitialized use occurs here
    719 |         struct dack *dack_script = (struct dack*)(&opt->data.dss.dack_dsn);
        |                                                    ^~~
  parser.y:710:8: note: remove the 'if' if its condition is always true
    710 |         }else if(dsn_type==8 && dack_type==8){
        |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  parser.y:710:11: error: variable 'opt' is used uninitialized whenever '&&' condition is false [-Werror,-Wsometimes-uninitialized]
    710 |         }else if(dsn_type==8 && dack_type==8){
        |                  ^~~~~~~~~~~
  parser.y:719:45: note: uninitialized use occurs here
    719 |         struct dack *dack_script = (struct dack*)(&opt->data.dss.dack_dsn);
        |                                                    ^~~
  parser.y:710:11: note: remove the '&&' if its condition is always true
    710 |         }else if(dsn_type==8 && dack_type==8){
        |                  ^~~~~~~~~~~~~~
  parser.y:688:24: note: initialize the variable 'opt' to silence this warning
    688 |         struct tcp_option *opt;
        |                               ^
        |                                = NULL
  2 errors generated.
  make: *** [Makefile.common:7: parser.o] Error 1

It looks like all these errors could lead to real issues.

Also, setting the port (u16) to -1 looks like a bad idea, but in theory,
the max (net.ipv4.ip_local_port_range) is not U16_MAX, so it looks OK.

Signed-off-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>